#! /bin/zsh
[ -z $ARCH ] && ARCH=amd64
[ -z $DIST ] && DIST=unstable
[ x"$DIST" = x"buster" ] && DIST=stable
[ x"$DIST" = x"bullseye" ] && DIST=testing
[ x"$DIST" = x"sid" ] && DIST=unstable
gbp buildpackage --git-ignore-new --git-builder="sbuild --arch=${ARCH} -d ${DIST}"
