#! /bin/zsh
path=( $HOME/.anyenv/bin(N-/)
       $path)
for dir in `ls $HOME/.anyenv/envs/` ; do
    if test -d $HOME/.anyenv/envs/$dir ; then
        path=( $HOME/.anyenv/envs/${dir}bin(N-/)
               $HOME/.anyenv/envs/${dir}shims(N-/)
               $path)
    fi
done
## for rbenv
typeset -gx RBENV_ROOT=$HOME/.anyenv/envs/rbenv
## for ndenv
typeset -gx NDENV_ROOT=$HOME/.anyenv/envs/ndenv

# cleanup duplicate
typeset -gxU path
