#! /bin/zsh
path=( ${path:#$HOME/.anyenv/bin*} )
typeset -gxU path
for dir in `ls $HOME/.anyenv/envs/` ; do
    if test -d $HOME/.anyenv/envs/$dir ; then
        path=( ${path:#$HOME/.anyenv/envs/${dir}bin*} )
        path=( ${path:#$HOME/.anyenv/envs/${dir}shims*} )
    fi
done
# for rbenv
unset RBENV_ROOT
typeset -gxU path
