#! /bin/zsh
[ -z $ARCH ] && ARCH=amd64
[ -z $DIST ] && DIST=unstable
[ x"$DIST" = x"bookworm" ] && DIST=stable
[ x"$DIST" = x"trixie" ] && DIST=testing
[ x"$DIST" = x"sid" ] && DIST=unstable
[ x"$EXT" = x"experimental"  ] && OPTS="--extra-repository='deb http://dennou-k.gfd-dennou.org/debian experimental main' --build-dep-resolver=aspcud"
[ ! -z $DEPS ] && OPTS="$OPTS --add-depends='$DEPS'"
echo gbp buildpackage --git-ignore-new --git-builder="sbuild --arch=${ARCH} -d ${DIST} $OPTS"
gbp buildpackage --git-ignore-new --git-builder="sbuild --arch=${ARCH} -d ${DIST} $OPTS"
