#! /bin/zsh
if (($+zle_bracketed_paste)); then
  print $zle_bracketed_paste[2]
fi
if which tac > /dev/null; then
    tac="tac"
else
    tac="tail -r"
fi
BUFFER=$(history -n 1 | eval $tac | awk '!a[$0]++' | peco --query "$LBUFFER")
CURSOR=$#BUFFER
zle reset-prompt
