#! /bin/zsh
#
_INTEL_VER=oneapi
_INTEL_PATH=/opt/intel/${_INTEL_VER}
## common
_INTEL_LICENSE_FILE=${_INTEL_PATH}/linux/licenses
_MANPATH=${_INTEL_PATH}/man/common
_LD_LIBRARY_PATH=${_INTEL_PATH}/linux/compiler/lib/intel64_lin
_NLSPATH=${_INTEL_PATH}/linux/compiler/lib/intel64/locale/%l_%t/%N
_PATH=${_INTEL_PATH}/linux/bin/intel64
_PATH=${_PATH}:${_INTEL_PATH}/linux/bin
## MPI
_I_MPI_ROOT=${_INTEL_PATH}/linux/mpi
_FI_PROVIDER_PATH=${_I_MPI_ROOT}/intel64/libfabric/lib/prov
_FI_PROVIDER_PATH=${_FI_PROVIDER_PATH}:/usr/lib64/libfabric
_MANPATH=${_MANPATH}:${_I_MPI_ROOT}/man
_LIBRARY_PATH=${_I_MPI_ROOT}/intel64/libfabric/lib
_LIBRARY_PATH=${_LIBRARY_PATH}:${_INTEL_PATH}/linux/compiler/lib/intel64_lin
_CLASSPATH=${_I_MPI_ROOT}/intel64/lib/mpi.jar
_LD_LIBRARY_PATH=${_LD_LIBRARY_PATH}:${_I_MPI_ROOT}/intel64/libfabric/lib
_LD_LIBRARY_PATH=${_LD_LIBRARY_PATH}:${_I_MPI_ROOT}/intel64/lib/release
_LD_LIBRARY_PATH=${_LD_LIBRARY_PATH}:${_I_MPI_ROOT}/intel64/lib
_PATH=${_PATH}:${_I_MPI_ROOT}/intel64/libfabric/bin
_PATH=${_PATH}:${_I_MPI_ROOT}/intel64/bin
## IPP
_IPPROOT=${_IPPROOT}
_LIBRARY_PATH=${_LIBRARY_PATH}:${_IPPROOT}/lib/intel64
_LD_LIBRARY_PATH=${_LD_LIBRARY_PATH}:${_IPPROOT}/lib/intel64
_CPATH=${_IPPROOT}/include
## MKL
_MKLROOT=${_INTEL_PATH}/linux/mkl
_LIBRARY_PATH=${_LIBRARY_PATH}:${_MKLROOT}/lib/intel64_lin
_LD_LIBRARY_PATH=${_LD_LIBRARY_PATH}:${_MKLROOT}/lib/intel64_lin
_PKG_CONFIG_PATH=${_MKLROOT}/bin/pkgconfig
_NLSPATH=${_NLSPATH}:${_MKLROOT}/lib/intel64_lin/locale/%l_%t/%N
_CPATH=${_CPATH}:${_MKLROOT}/include
## TBB
_TBBROOT=${_INTEL_PATH}/linux/tbb
_LIBRARY_PATH=${_LIBRARY_PATH}:${_TBBROOT}/lib/intel64/gcc4.8
_LIBRARY_PATH=${_LIBRARY_PATH}:${_TBBROOT}/lib/intel64/gcc4.8
_LD_LIBRARY_PATH=${_LD_LIBRARY_PATH}:${_TBBROOT}/lib/intel64/gcc4.8
_CPATH=${_CPATH}:${_TBBROOT}/include
_CPATH=${_CPATH}:${_TBBROOT}/include
# DAAL
_DAALROOT=${_INTEL_PATH}/linux/daal
_LIBRARY_PATH=${_LIBRARY_PATH}:${_DAALROOT}/lib/intel64_lin
_LIBRARY_PATH=${_LIBRARY_PATH}:${_DAALROOT}/../tbb/lib/intel64_lin/gcc4.4
_LIBRARY_PATH=${_LIBRARY_PATH}:${_DAALROOT}/../tbb/lib/intel64_lin/gcc4.8
_LD_LIBRARY_PATH=${_LD_LIBRARY_PATH}:${_DAALROOT}/lib/intel64_lin
_LD_LIBRARY_PATH=${_LD_LIBRARY_PATH}:${_DAALROOT}/../tbb/lib/intel64_lin/gcc4.4
_LD_LIBRARY_PATH=${_LD_LIBRARY_PATH}:${_DAALROOT}/../tbb/lib/intel64_lin/gcc4.8
_CLASSPATH=${_CLASSPATH}:${_DAALROOT}/lib/daal.jar
_CPATH=${_CPATH}:${_DAALROOT}/include
## PSTL
_PSTLROOT=${_INTEL_PATH}/linux/pstl
_CPATH=${_CPATH}:${_PSTLROOT}/include
_CPATH=${_CPATH}:${_PSTLROOT}/stdlib
## INTEL PYTHON
_INTEL_PYTHONHOME=${_INTEL_PATH}/debugger_2020/python/intel64/
_LD_LIBRARY_PATH=${_LD_LIBRARY_PATH}:${_INTEL_PYTHONHOME}/lib
## Intel Debugger
_LD_LIBRARY_PATH=${_LD_LIBRARY_PATH}:${_INTEL_PATH}/debugger_2020/libipt/intel64/lib
_MANPATH=${_MANPATH}:${_INTEL_PATH}/documentation_2020/en/debugger/gdb-ia/man/
_INFOPATH=${_INTEL_PATH}/documentation_2020/en/debugger/gdb-ia/info/
_NLSPATH=${_NLSPATH}:${_INTEL_PATH}/debugger_2020/gdb/intel64/share/locale/%l_%t/%N
_PATH=${_PATH}:${_INTEL_PATH}/debugger_2020/gdb/intel64/bin
_MKL_LIBS="-L${MKLROOT}/lib/intel64 -lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm -ldl"
